CREATE OR REPLACE WAREHOUSE ECOMM_WH 
WITH WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE ECOMM_DB;
CREATE OR REPLACE SCHEMA ECOMM_DB.SALES;

USE WAREHOUSE ECOMM_WH;
USE DATABASE ECOMM_DB;
USE SCHEMA SALES;
